public void postuser() {
		//imp-
		Response response = UserEndPoints.CreateUser(userPayload);
		response.then().log().all();
		Assert.assertEquals(response.getStatusCode(), 200);
		 System.out.println("POST username: " + this.userPayload.getUsername());

	}